// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: customer_logs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomerLogs = `-- name: CreateCustomerLogs :one
INSERT INTO customer_logs(
    id,
    customer_id,
    user_id,
    customer_account_id,
    transaction_type,
    created_at,
    updated_at,
    is_deleted,
    deleted_at
)VALUES(
    $1,$2,$3,$4,$5,$6,$7,$8,$9
)RETURNING id, customer_id, user_id, customer_account_id, transaction_type, created_at, updated_at, is_deleted, deleted_at
`

type CreateCustomerLogsParams struct {
	ID                uuid.UUID `json:"id"`
	CustomerID        uuid.UUID `json:"customer_id"`
	UserID            uuid.UUID `json:"user_id"`
	CustomerAccountID uuid.UUID `json:"customer_account_id"`
	TransactionType   string    `json:"transaction_type"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	IsDeleted         bool      `json:"is_deleted"`
	DeletedAt         time.Time `json:"deleted_at"`
}

func (q *Queries) CreateCustomerLogs(ctx context.Context, arg CreateCustomerLogsParams) (CustomerLog, error) {
	row := q.db.QueryRow(ctx, createCustomerLogs,
		arg.ID,
		arg.CustomerID,
		arg.UserID,
		arg.CustomerAccountID,
		arg.TransactionType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsDeleted,
		arg.DeletedAt,
	)
	var i CustomerLog
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.UserID,
		&i.CustomerAccountID,
		&i.TransactionType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}
