// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: users_logs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserLogs = `-- name: CreateUserLogs :one
INSERT INTO users_logs(
    id,
    customer_id,
    user_id,
    customer_account_id,
    transaction_type,
    transaction_purpose,
    created_at,
    updated_at,
    is_deleted,
    deleted_at
)VALUES(
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10
)RETURNING id, customer_id, user_id, customer_account_id, transaction_type, transaction_purpose, created_at, updated_at, is_deleted, deleted_at
`

type CreateUserLogsParams struct {
	ID                 uuid.UUID `json:"id"`
	CustomerID         uuid.UUID `json:"customer_id"`
	UserID             uuid.UUID `json:"user_id"`
	CustomerAccountID  uuid.UUID `json:"customer_account_id"`
	TransactionType    string    `json:"transaction_type"`
	TransactionPurpose string    `json:"transaction_purpose"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	IsDeleted          bool      `json:"is_deleted"`
	DeletedAt          time.Time `json:"deleted_at"`
}

func (q *Queries) CreateUserLogs(ctx context.Context, arg CreateUserLogsParams) (UsersLog, error) {
	row := q.db.QueryRow(ctx, createUserLogs,
		arg.ID,
		arg.CustomerID,
		arg.UserID,
		arg.CustomerAccountID,
		arg.TransactionType,
		arg.TransactionPurpose,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsDeleted,
		arg.DeletedAt,
	)
	var i UsersLog
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.UserID,
		&i.CustomerAccountID,
		&i.TransactionType,
		&i.TransactionPurpose,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}
